version: '3.8'
services:
  tarmac-example:
    image: madflojo/tarmac
    ports:
      - 80:8080
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_LISTEN_ADDR=0.0.0.0:8080"
    volumes:
      - "./module:/module"
  builder:
    image: tinygo/tinygo
    volumes:
      - "./:/src"
    command: tinygo build -o module/tarmac_module.wasm -target wasi ./main.go
