name: build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Install cover
      run: go get golang.org/x/tools/cmd/cover
    - name: Install goveralls
      run: go get -u github.com/mattn/goveralls
    - name: Execute Tests
      run: make tests
    - name: Update Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage/coverage.out -service=github
