name: tests

on:
  push:
    #branches: [ $default-branch ]
    branches:
      - actions 
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Execute Tests
      run: make tests
