name: tests

on:
  push:
    #branches: [ $default-branch ]
    branches: *
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: parisk/setup-compose-cli@v1

    - name: Execute Tests
      run: make tests
